// import { Icon } from '@chakra-ui/react'
// import { OneInch, BNB, Optimism, Ethereum } from '../components/Icons/CryptoIcons'
export const tableData = [
  {
    id: 0,
    allocated: 420000,
    category: "Utilities",
    inBallots: 109,
    inLists: 14,
    project: {
      href: "#",
      name: "Solidity",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
        // { id: 2, src: <Icon as={Optimism} />, title: 'Optimism' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 1,
        color: { bg: "rgba(255, 175, 175, 1)", txt: "rgba(156, 36, 36, 1)" },
        title: "OP STACK",
        value: 3,
      },
    ],
  },
  {
    id: 1,
    allocated: 300000,
    category: "Utilities +1",
    inBallots: 109,
    inLists: 14,
    project: {
      href: "#",
      name: "ethers.js",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
    ],
  },
  {
    id: 2,
    allocated: 170000,
    category: "Utilities",
    inBallots: 101,
    inLists: 10,
    project: {
      href: "#",
      name: "Otterscan",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' }
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(255, 234, 150, 1)", txt: "rgba(156, 124, 0, 1)" },
        title: "END UX",
        value: 2,
      },
      {
        id: 1,
        color: { bg: "rgba(255, 175, 175, 1)", txt: "rgba(156, 36, 36, 1)" },
        title: "OP STACK",
        value: 3,
      },
    ],
  },
  {
    id: 3,
    allocated: 280000,
    category: "Utilities",
    inBallots: 101,
    inLists: 10,
    project: {
      href: "#",
      name: "Hardhat",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
        // { id: 2, src: <Icon as={Optimism} />, title: 'Optimism' },
        // { id: 3, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 4, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 5, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 6, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 7, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 8, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 9, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 10, src: <Icon as={Ethereum} />, title: 'Ethereum' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 1,
        color: { bg: "rgba(255, 175, 175, 1)", txt: "rgba(156, 36, 36, 1)" },
        title: "OP STACK",
        value: 3,
      },
    ],
  },
  {
    id: 4,
    allocated: 500000,
    category: "Utilities",
    inBallots: 101,
    inLists: 15,
    project: {
      href: "#",
      name: "go-ethereum",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
        // { id: 2, src: <Icon as={Optimism} />, title: 'Optimism' },
        // { id: 3, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 4, src: <Icon as={Ethereum} />, title: 'Ethereum' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 1,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 2,
        color: { bg: "rgba(255, 234, 150, 1)", txt: "rgba(156, 124, 0, 1)" },
        title: "END UX",
        value: 2,
      },
    ],
  },
  {
    id: 5,
    allocated: 200000,
    category: "Utilities",
    inBallots: 99,
    inLists: 16,
    project: {
      href: "#",
      name: "L2BEAT 💗",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
        // { id: 2, src: <Icon as={Optimism} />, title: 'Optimism' },
        // { id: 3, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 4, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 5, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 6, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 7, src: <Icon as={Ethereum} />, title: 'Ethereum' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(150, 191, 252, 1)", txt: "rgba(0, 60, 151, 1)" },
        title: "COLL GOV",
        value: 0,
      },
      {
        id: 1,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 2,
        color: { bg: "rgba(255, 234, 150, 1)", txt: "rgba(156, 124, 0, 1)" },
        title: "END UX",
        value: 2,
      },
    ],
  },
  {
    id: 6,
    allocated: 250000,
    category: "Utilities",
    inBallots: 97,
    inLists: 11,
    project: {
      href: "#",
      name: "Vyper",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
        // { id: 2, src: <Icon as={Optimism} />, title: 'Optimism' },
        // { id: 3, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 4, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 5, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 6, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 7, src: <Icon as={Ethereum} />, title: 'Ethereum' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 1,
        color: { bg: "rgba(255, 175, 175, 1)", txt: "rgba(156, 36, 36, 1)" },
        title: "OP STACK",
        value: 3,
      },
    ],
  },
  {
    id: 7,
    allocated: 660000,
    category: "Utilities",
    inBallots: 95,
    inLists: 13,
    project: {
      href: "#",
      name: "Protocol Guild",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
        // { id: 2, src: <Icon as={Optimism} />, title: 'Optimism' },
        // { id: 3, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 4, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 5, src: <Icon as={Ethereum} />, title: 'Ethereum' },
        // { id: 6, src: <Icon as={Ethereum} />, title: 'Ethereum' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 1,
        color: { bg: "rgba(255, 234, 150, 1)", txt: "rgba(156, 124, 0, 1)" },
        title: "END UX",
        value: 2,
      },
      {
        id: 2,
        color: { bg: "rgba(255, 175, 175, 1)", txt: "rgba(156, 36, 36, 1)" },
        title: "OP STACK",
        value: 3,
      },
    ],
  },
  {
    id: 8,
    allocated: 250000,
    category: "Utilities",
    inBallots: 93,
    inLists: 14,
    project: {
      href: "#",
      name: "DefiLlama",
      cryptosImg: [],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 1,
        color: { bg: "rgba(255, 234, 150, 1)", txt: "rgba(156, 124, 0, 1)" },
        title: "END UX",
        value: 2,
      },
    ],
  },
  {
    id: 9,
    allocated: 220000,
    category: "Utilities",
    inBallots: 94,
    inLists: 10,
    project: {
      href: "#",
      name: "beaconcha.in",
      cryptosImg: [
        // { id: 0, src: <Icon as={OneInch} />, title: 'OneInch' },
        // { id: 1, src: <Icon as={BNB} />, title: 'BNB' },
      ],
      src: "/assets/images/default-img.png",
    },
    tags: [
      {
        id: 0,
        color: { bg: "rgba(153, 230, 196, 1)", txt: "rgba(4, 118, 68, 1)" },
        title: "DEV ECO",
        value: 1,
      },
      {
        id: 1,
        color: { bg: "rgba(255, 234, 150, 1)", txt: "rgba(156, 124, 0, 1)" },
        title: "END UX",
        value: 2,
      },
      {
        id: 2,
        color: { bg: "rgba(255, 175, 175, 1)", txt: "rgba(156, 36, 36, 1)" },
        title: "OP STACK",
        value: 3,
      },
    ],
  },
];
